// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbyqrmusfuyauyicefbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNieXFybXVzZnV5YXV5aWNlZmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NzU3NTgsImV4cCI6MjA2MDI1MTc1OH0.S7iZA0u1yi1bf02a7Myuj_zbrglgMxCa_PJEUaHldkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});